account/urls.py
from django.urls import path, reverse_lazy, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('account:password_change_done')),
        name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('account:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('account:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('', views.dashboard, name='dashboard'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'project.views.page_handler404'
handler500 = 'project.views.page_handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('trainer.urls', namespace='trainer')),
    path('vote/', include('like_dislike.urls', namespace='like_dislike')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainer/urls.py
from django.urls import path, reverse_lazy, include
from . import views
from .views import *

app_name = 'trainer'

urlpatterns = [
    path('', HomeView.as_view(), name='home-page'),
    path('trainers/', TrainerListView.as_view(), name='trainers-list'),
    path('trainer/<slug:slug>', TrainerDetailView.as_view(), name='trainer-detail'),
    path('book/', BookView.as_view(), name='event-book'),
    path('add_comment/', AddCommentView.as_view(), name='add-comment'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event-detail'),
    path('events/', EventListView.as_view(), name='events-list'),
    path('events/tag/<slug:tag_slug>/', EventListView.as_view(), name='events-list-by-tag'),
]

trainer/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse
from django_resized import ResizedImageField
from datetime import datetime
from django.utils import timezone
from taggit.managers import TaggableManager
from like_dislike.models import LikeDislike


class ActivedManager(models.Manager):
    """Менеджер который фильтрует только активные (active=True) записи"""

    def get_queryset(self):
        return super().get_queryset().filter(active=True)


class ActivedEventManager(models.Manager):
    """Менеджер возвращает только активные события.
    Это события у которых active=True и дата/время начала больше текущего времени"""

    def get_queryset(self):
        return super().get_queryset().filter(active=True).filter(start__gt=datetime.now(tz=timezone.utc))


class Trainer(models.Model):
    """Модель хранит информацию о тренерах"""

    name = models.CharField(max_length=50, verbose_name="Имя тренера", help_text="Имя и фамилия тренера")
    slug = models.SlugField(max_length=50, unique=True, verbose_name="Слаг",
                            help_text="Уникальный постфикс тренера в урл-е")
    description = models.TextField(verbose_name="О тренере", help_text="Укажите краткую биографию тренера")
    avatar = ResizedImageField(size=[300, None], upload_to='trainers/%Y/%m/%d/', blank=True, null=True,
                               verbose_name="Фотография")
    active = models.BooleanField(default=True, verbose_name="Вкл/Выкл",
                                 help_text="Флаг публикующий тренера на сайте")
    votes = GenericRelation(LikeDislike, related_query_name='trainers')

    objects = models.Manager()
    actived = ActivedManager()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f"Trainer {self.name}"

    def get_absolute_url(self):
        return reverse('trainer:trainer-detail', args=[self.slug])


class Event(models.Model):
    """Модель хранит информацию об событиях"""

    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, related_name='events', verbose_name="Тренер")
    user = models.ManyToManyField(User, blank=True, verbose_name="Пользователь")
    name = models.CharField(max_length=50, verbose_name="Название события")
    description = models.TextField(verbose_name="О событии")
    start = models.DateTimeField(verbose_name="Дата/время начала")
    end = models.DateTimeField(verbose_name="Дата/время окончания")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    total_places = models.PositiveSmallIntegerField(verbose_name="Количество мест")
    active = models.BooleanField(default=False, verbose_name="Вкл/Выкл",
                                 help_text="Флаг публикующий событие на сайте")
    tags = TaggableManager(verbose_name="Теги")

    objects = models.Manager()
    actived = ActivedEventManager()

    class Meta:
        ordering = ['-start']

    def __str__(self):
        return f"Event '{self.name}' of trainer '{self.trainer.name}'"

    def get_absolute_url(self):
        return reverse('trainer:event-detail', args=[self.pk])

    @property
    def booked(self):
        return self.user.count()


class Comment(models.Model):
    """Модель хранит информацию о комментариях пользователей к тренерам"""

    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, related_name='comments', verbose_name="Тренер")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    body = models.TextField(verbose_name="Комментарий")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    active = models.BooleanField(default=True, verbose_name="Вкл/Выкл",
                                 help_text="Флаг публикующий комментарий на сайте")
    votes = GenericRelation(LikeDislike, related_query_name='comments')

    objects = models.Manager()
    actived = ActivedManager()

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Id #{self.pk} of {self.trainer}'

trainer/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    """Форма создания комментариев к странице тренера"""

    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={"rows": "3"}),
        }

trainer/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, FormView, TemplateView
from trainer.forms import CommentForm
from trainer.models import Trainer, Event
from trainer.services.service_comment import ServiceComment
from trainer.services.service_event import ServiceEvent
from trainer.services.service_tag import ServiceTag
from trainer.services.service_trainer import ServiceTrainer
from trainer.utils import PaginateMixin


class HomeView(TemplateView):
    """Главная страница"""

    template_name = 'trainer/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trainers'] = ServiceTrainer.get_random_trainers()
        context['events'] = ServiceEvent.get_events(limit=ServiceEvent.ROWS_HOME_LIMIT)
        return context


class TrainerListView(PaginateMixin, ListView):
    """Страница с списком тренеров"""

    model = Trainer
    template_name = 'trainer/trainers.html'
    queryset = ServiceTrainer.get_trainers()
    context_object_name = 'trainers'
    paginate_by = ServiceTrainer.ROWS_LIMIT


class TrainerDetailView(DetailView):
    """Детальная страница тренера"""

    model = Trainer
    template_name = 'trainer/trainer_detail.html'
    context_object_name = 'trainer'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['event_list'] = ServiceEvent.get_events(trainer=self.object)
        context['form'] = CommentForm()
        context['page_obj'] = ServiceComment.get_all_by_trainer(
            trainer=self.object,
            page_number=self.request.GET.get('page')
        )
        return context


class EventListView(ListView):
    """Страница списка событий"""

    model = Event
    template_name = 'trainer/events.html'
    context_object_name = 'events'
    paginate_by = ServiceEvent.ROWS_LIMIT

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = ServiceTag.get_all()
        return context

    def get_queryset(self):
        return ServiceEvent.get_events(tag_slug=self.kwargs.get('tag_slug', None))


class EventDetailView(DetailView):
    """Детальная страница события"""

    model = Event
    template_name = 'trainer/event_detail.html'
    context_object_name = 'event'

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        return Event.actived.all().filter(pk=pk).prefetch_related('user')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object.book_places = self.object.total_places - self.object.user.count()
        return context


class BookView(View):
    """Бронирование события. Методом POST пользователь подписывается на событие"""

    def post(self, request):
        user_id = int(request.POST.get('user_id', 0))
        event_id = int(request.POST.get('event_id', 0))
        if not user_id or not event_id or request.user.id != user_id:
            raise ValueError("Incorrect booking data")

        ServiceEvent.add_user_to_event(event_id=event_id, user=request.user)
        event = ServiceEvent.get_event_by_id(event_id=event_id)
        messages.success(request, f"You successfully booked on - {event}")

        return HttpResponseRedirect(request.POST.get('next', '/'))


class AddCommentView(FormView):
    """Добавление комментария тренеру"""

    form_class = CommentForm
    trainer = None

    def get_success_url(self):
        if self.trainer:
            return reverse('trainer:trainer-detail', args=[self.trainer.slug])
        else:
            return reverse('trainer:trainers-list')

    def form_valid(self, form):
        self.trainer = ServiceTrainer.get_trainer_by_id(
            trainer_id=self.request.POST.get('trainer_id')
        )
        if not self.trainer:
            messages.error(self.request, "Cannot added comment. Trainer isn't choosed.")
        else:
            ServiceComment.add_comment(
                comment=form.save(commit=False),
                trainer=self.trainer,
                user=self.request.user
            )
            messages.success(self.request, "Your comment successfully added")

        return super().form_valid(form)

trainer/templates/trainer/event_detail.html
{% extends "base.html" %}

{% block title %}Event / {{event.name}} {% endblock %}

{% block page_title %} {{event.name}} {% endblock %}

{% block content %}
    {% load trainer_extras %}
    <table>
        <tbody>
        <tr>
            <td style="vertical-align: top;">
            <img src="{{ MEDIA_URL }}{{ event.trainer.avatar }}" alt="{{ event.trainer.name }}" title="{{ event.trainer.name }}" />
            </td>
            <td style="padding: 30px; vertical-align: top;">
                <h3>About Event</h3>

                <p>Tags: {{ event.tags.all|join:', ' }}</p>
                <p>{{ event.description|linebreaks }}</p>
                <p>Start: <b>{{ event.start|formated_date }}</b></p>
                <p>End: <b>{{ event.end|formated_date }}</b></p>
                <p>Price: <b>{{ event.price }}</b></p>
                <p>Total places: <b>{{ event.total_places }}</b></p>
                <p>Booked users:
                    {% for user in event.user.all %}
                        <i>{{ user.first_name|default:user.username }}{% if not forloop.last %}, {% endif %}</i>
                    {% empty %}
                        Nobody
                    {% endfor %}
                </p>
                <p>Places left: <b>{{ event.book_places }}</b></p>
                <p>
                    {% if request.user in event.user.all %}
                        Booked
                    {% else %}
                        <form action="{% url 'trainer:event-book' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="user_id" value="{{ request.user.pk }}" />
                            <input type="hidden" name="event_id" value="{{ event.pk }}" />
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button class="btn btn-sm btn-primary" type="submit">Book</button>
                          </form>
                    {% endif %}
                </p>
            </td>
        </tr>
        </tbody>
    </table>

{% endblock %}

trainer/templates/trainer/events.html
{% extends "base.html" %}

{% block title %}Events / List{% endblock %}

{% block page_title %}All Events{% endblock %}

{% block content %}
    {% load trainer_extras %}

<div>
    Tags: <a href="{% url 'trainer:events-list' %}">all</a>,
{% for tag in tags.all %}
<a href="{% url 'trainer:events-list-by-tag' tag.slug %}">
{{ tag.name }}
</a>
{% if not forloop.last %}, {% endif %}
{% endfor %}
</div>

    <table width="100%" class="mt-2">
        <thead>
            <tr>
                <td style="padding-bottom: 10px">
                    <b>Trainer</b>
                </td>
                <td>
                    <b>Event name</b>
                </td>
                <td>
                    <b>Tags</b>
                </td>
                <td>
                    <b>Start date/time</b>
                </td>
                <td>
                    <b>End date/time</b>
                </td>
                <td>
                    <b>Price</b>
                </td>
                <td>
                    <b>Places</b>
                </td>
                <td></td>
            </tr>
        <tbody>
        {% for event in events %}
        <tr>
            <td style="padding-bottom: 10px">
                <b>{{ event.trainer.name }}</b>
            </td>
            <td>
                <b>{{ event.name }}</b>
            </td>
            <td>
                {{ event.tags.all|join:', ' }}
            </td>
            <td>
                {{ event.start|formated_date }}
            </td>
            <td>
                {{ event.end|formated_date }}
            </td>
            <td>
                {{ event.price }}
            </td>
            <td>
                {{ event.book_places }}
            </td>
            <td>
                {% if event.book_places > 0 %}
                    <a href="{{ event.get_absolute_url }}">Detail</a>
                {% else %}
                    Sold out
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include "includes/pagination.html" %}

{% endblock %}

trainer/templates/trainer/home.html
{% extends "base.html" %}

{% block title %}Home page {% endblock %}

{% block page_title %} Home {% endblock %}

{% block content %}
{% load trainer_extras %}
<h3>Trainers</h3>
<div class="container">
    <div class="row align-items-start">
    {% for trainer in trainers %}
    <div class="col">
        <div>{{ trainer.name }}</div>
        {% if trainer.avatar %}
        <a href="{{ trainer.get_absolute_url }}">
            <img src="{{ trainer.avatar.url }}" width="200" alt="{{ trainer.name }}" title="{{ trainer.name }}" />
        </a>
        {% endif %}
    </div>
    {% endfor %}
    </div>
    <a href="{% url 'trainer:trainers-list' %}">All trainers</a>
</div>
<br><br><br>
<h3>Events</h3>
<div class="container">

    <table width="100%" class="mt-2">
        <thead>
            <tr>
                <td style="padding-bottom: 10px">
                    <b>Trainer</b>
                </td>
                <td>
                    <b>Event name</b>
                </td>
                <td>
                    <b>Tags</b>
                </td>
                <td>
                    <b>Start date/time</b>
                </td>
                <td>
                    <b>End date/time</b>
                </td>
                <td>
                    <b>Price</b>
                </td>
                <td>
                    <b>Places</b>
                </td>
                <td></td>
            </tr>
        <tbody>
        {% for event in events %}
        <tr>
            <td style="padding-bottom: 10px">
                <b>{{ event.trainer.name }}</b>
            </td>
            <td>
                <b>{{ event.name }}</b>
            </td>
            <td>
                {{ event.tags.all|join:', ' }}
            </td>
            <td>
                {{ event.start|formated_date }}
            </td>
            <td>
                {{ event.end|formated_date }}
            </td>
            <td>
                {{ event.price }}
            </td>
            <td>
                {{ event.book_places }}
            </td>
            <td>
                {% if event.book_places > 0 %}
                    <a href="{{ event.get_absolute_url }}">Detail</a>
                {% else %}
                    Sold out
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'trainer:events-list' %}">All events</a>
    </div>
</div>

{% endblock %}

trainer/templates/trainer/trainer_detail.html
{% extends "base.html" %}

{% block title %}Trainer / {{trainer.name}} {% endblock %}

{% block page_title %} {{trainer.name}} {% endblock %}

{% block content %}
    {% csrf_token %}
    {% load trainer_extras %}
    <table>
        <tbody>
        <tr>
            <td style="vertical-align: top;">
            {% if trainer.avatar %}
                <img src="{{ trainer.avatar.url }}" alt="{{ trainer.name }}" title="{{ trainer.name }}" />
            {% endif %}
            </td>
            <td style="padding: 30px; vertical-align: top;">
                {{ trainer.description|linebreaks }}

                {% if event_list %}
                <h3>Events</h3>
                <table width="100%">
                <thead>
                    <tr>
                        <td style="padding-bottom: 10px">
                            <b>Name</b>
                        </td>
                        <td>
                            <b>Start date/time</b>
                        </td>
                        <td>
                            <b>End date/time</b>
                        </td>
                        <td>
                            <b>Price</b>
                        </td>
                        <td>
                            <b>Places</b>
                        </td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    {% for event in event_list %}
                    <tr>
                        <td style="padding-bottom: 10px">
                            {{ event.name }}
                        </td>
                        <td>
                            {{ event.start|formated_date }}
                        </td>
                        <td>
                            {{ event.end|formated_date }}
                        </td>
                        <td>
                            {{ event.price }}
                        </td>
                        <td>
                            {{ event.book_places }}
                        </td>
                        <td>
                            {% if event.book_places > 0 %}
                                <a href="{{ event.get_absolute_url }}">Detail</a>
                            {% else %}
                                Sold out
                            {% endif %}

                            {% comment %}
                            {% if request.user in event.user.all %}
                                Booked
                            {% else %}
                                <form action="{% url 'trainer:event-book' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="user_id" value="{{ request.user.pk }}" />
                                    <input type="hidden" name="event_id" value="{{ event.pk }}" />
                                    <input type="hidden" name="next" value="{{ request.path }}">
                                    <button class="btn btn-sm btn-primary" type="submit">Book</button>
                                  </form>
                            {% endif %}
                            {% endcomment %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                </table>
                {% endif %}
                {% include "like_dislike/includes/container.html" with pk=trainer.pk model="trainer" like_count=trainer.votes.like_count dislike_count=trainer.votes.dislike_count %}

                {% if request.user.is_authenticated %}
                <div class="mt-2">
                <h3>Add comment</h3>
                <form action="{% url 'trainer:add-comment' %}" method="post">
                {{ form.as_p }}
                {% csrf_token %}
                    <input type="hidden" name="trainer_id" value="{{ trainer.pk }}" />
                <p><input type="submit" class="btn btn-sm btn-primary" value="Add comment"></p>
                </form>
                </div>
                {% endif %}

                {% if page_obj %}
                <div class="mt-2">
                    <h3>Comments</h3>
                    {% for comment in page_obj %}
                    <div style="border-bottom: 1px solid gray">
                        <p>
                            Username: <i>{{ comment.user.username }}</i> <i>({{ comment.created|formated_date }})</i>
                        </p>
                        {{ comment.body|linebreaks }}
                    </div>
                    {% include "like_dislike/includes/container.html" with pk=comment.pk model="comment" like_count=comment.votes.like_count dislike_count=comment.votes.dislike_count %}
                    {% endfor %}
                </div>
                {% include "includes/pagination.html" %}
                {% endif %}

            </td>
        </tr>
        </tbody>
    </table>

{% endblock %}

{% load static %}
{% block scripts %}
<script src="{% static 'like_dislike/js/manage.js' %}"></script>
{% endblock %}

trainer/templates/trainer/trainers.html
{% extends "base.html" %}

{% block title %}Trainers / List{% endblock %}

{% block page_title %}Trainers{% endblock %}

{% block content %}

    <table>
        <tbody>
        {% for trainer in trainers %}
        <tr>
            <td style="padding-bottom: 30px">
            {% if trainer.avatar %}
            <img src="{{ trainer.avatar.url }}" width="200" alt="{{ trainer.name }}" title="{{ trainer.name }}" />
            {% endif %}
            </td>
            <td style="padding: 30px; vertical-align: top;">
                <h3>
                    <a href="{{ trainer.get_absolute_url }}">{{ trainer.name }}</a>
                </h3>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include "includes/pagination.html" %}

{% endblock %}