account/urls.py
from django.urls import path, reverse_lazy, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('account:password_change_done')),
        name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('account:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('account:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('', views.dashboard, name='dashboard'),
]

contact/urls.py
from django.urls import path, include
from contact.views import ContactFormView, ContactThanksView

app_name = 'contact'

urlpatterns = [
    path('', ContactFormView.as_view(), name='form'),
    path('thanks/', ContactThanksView.as_view(), name='thanks'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'project.views.page_handler404'
handler500 = 'project.views.page_handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('trainer.urls', namespace='trainer')),
    path('vote/', include('like_dislike.urls', namespace='like_dislike')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainer/urls.py
from django.urls import path, reverse_lazy, include
from . import views
from .views import *

app_name = 'trainer'

urlpatterns = [
    path('', HomeView.as_view(), name='home-page'),
    path('trainers/', TrainerListView.as_view(), name='trainers-list'),
    path('trainer/<slug:slug>', TrainerDetailView.as_view(), name='trainer-detail'),
    path('book/', BookView.as_view(), name='event-book'),
    path('add_comment/', AddCommentView.as_view(), name='add-comment'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event-detail'),
    path('events/', EventListView.as_view(), name='events-list'),
    path('events/tag/<slug:tag_slug>/', EventListView.as_view(), name='events-list-by-tag'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
</head>
<body>
<div class="container">

    <nav class="py-2 bg-light border-bottom">
    <div class="container d-flex flex-wrap">
      <ul class="nav me-auto">
        <li class="nav-item"><a href="{% url 'trainer:home-page' %}" class="nav-link link-dark px-2 active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="{% url 'trainer:trainers-list' %}" class="nav-link link-dark px-2">Trainers</a></li>
        <li class="nav-item"><a href="{% url 'trainer:events-list' %}" class="nav-link link-dark px-2">Events</a></li>
        <li class="nav-item"><a href="{% url 'contact:form' %}" class="nav-link link-dark px-2">Contact</a></li>
      </ul>
        {% if request.user.is_authenticated %}
        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            {% if request.user.profile.avatar %}
            <img src="{{ MEDIA_URL }}{{request.user.profile.avatar}}" alt="mdo" width="32" height="32" class="rounded-circle">
            {% else %}
            Hello {{ request.user.first_name|default:request.user.username }}
            {% endif %}
          </a>
          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="{% url 'account:dashboard' %}">Dashboard</a></li>
            <li><a class="dropdown-item" href="{% url 'account:edit' %}">Edit</a></li>
            <li><a class="dropdown-item" href="{% url 'account:password_change' %}">Change your password</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'account:logout' %}">Sign out</a></li>
          </ul>
        </div>
        {% else %}
          <a class="nav-link link-dark px-2" href="{% url 'account:login' %}">Log-in</a>
          <a class="nav-link link-dark px-2" href="{% url 'account:register' %}">Register</a>
        {% endif %}

  </nav>
  <header class="py-3 mb-4">
  </header>
  {% bootstrap_messages %}

  <h1 class="mb-4">{% block page_title %}{% endblock %}</h1>

  {% block content %}
  {% endblock %}
</div>
{% block scripts %}
{% endblock %}
</body>
</html>

templates/base_account.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>

  <style>
    html,
    body {
      height: 100%;
    }

    body {
      display: flex;
      align-items: center;
      padding-top: 40px;
      padding-bottom: 40px;
      background-color: #f5f5f5;
    }

    .form-container {
      width: 100%;
      max-width: 550px;
      padding: 15px;
      margin: auto;
    }

    .form-container .form-floating:focus-within {
      z-index: 2;
    }

    .errorlist {
      color: red
    }
  </style>

</head>
<body class="text-center">
  <main class="form-container">
    <h1>{% block form_title %}{% endblock %}</h1>
    <div class="col shadow p-3 mb-0 bg-body rounded">
      {% block content %}{% endblock %}
    </div>
  </main>
</body>
</html>